Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro # In runtime adding the params to change the instance type form micro to small
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: "default" # keypair must already exist
      ImageId: ami-6869aa05 # AMI us-east-1
