AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          S3_BUCKET: cloudformation-tsabunkar
      CodeUri: s3://cloudformation-tsabunkar/e7d7a84c0c770bf37a85fc026dd01e4a
